# Generated by Django 5.0.6 on 2024-05-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(help_text='Sotuvchining foydalanuvchi nomi', max_length=50, unique=True),
        ),
    ]
